
spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/gnd_ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 20552789ec00f6
    password: 5bd4da051bf994
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: sandbox.smtp.mailtrap.io



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: e34fafbc0a503765095f524e8e8eb8af9d9d7ceb263df39ea9ce1e3b426e651e

server:
  port: 8080

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

